//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiGK_63132946.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANAO
    {
        public string MaQA { get; set; }
        public string TenQA { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> XuatXu { get; set; }
        public double DonGia { get; set; }
        public string AnhMH { get; set; }
        public string MaLQA { get; set; }
    
        public virtual LOAIQUANAO LOAIQUANAO { get; set; }
    }
}
