//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap6_63132946.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [DisplayName("Mã số nhân viên")]
        [Required(ErrorMessage ="Chưa nhập mã nhân viên")]
        public string MaNV { get; set; }
        [DisplayName("Họ nhân viên")]
        [Required(ErrorMessage = "Chưa nhập họ nhân viên")]
        public string HoNV { get; set; }
        [DisplayName("Tên nhân viên")]
        [Required(ErrorMessage = "Chưa nhập tên nhân viên")]
        public string TenNV { get; set; }
        [DisplayName("Giới tính")]
        public Nullable<bool> GioiTinh { get; set; }
        [DisplayName("Ngày sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [DisplayName("Lương")]
        public Nullable<int> Luong { get; set; }
        [DisplayName("Ảnh nhân viên")]
        public string AnhNV { get; set; }
        [DisplayName("Địa Chỉ")]
        public string DiaChi { get; set; }
        [DisplayName("Phòng ban")]
        public string MaPB { get; set; }
    
        public virtual PhongBan PhongBan { get; set; }
    }
}
