//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHighLands63132946.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public string maBill { get; set; }
        public int tong { get; set; }
        public string maNV { get; set; }
        public string maMon { get; set; }
        public string maKH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual THUCDON THUCDON { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
