//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHighLands63132946.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUCDON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUCDON()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public string maMon { get; set; }
        public string tenMon { get; set; }
        public double gia { get; set; }
        public string hinhAnh { get; set; }
        public string maNCC { get; set; }
        public string maLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
